### ISSUE TITLE
Build fails when configured for x86

### ISSUE THREAD

**Issue by cppcooper** [JochenKalmbach/StackWalker#28]
https://github.com/JochenKalmbach/StackWalker/blob/020706a2972bff842d8976ef81825f57e197eea5/Main/StackWalker/StackWalker.h#L227-L239
This macro causes errors in the build.

```
stackwalker.cpp(1071): error C2400: inline assembler syntax error in 'first operand'; found ':'
```

Removing the label and call results in errors as well.

**Comment by matlo607** [comment]
@cppcooper, I am sincerely sorry, I introduced a regression in https://github.com/JochenKalmbach/StackWalker/commit/0561ee5c30c6fac9d71c97c2c97004533c1d3e7a#diff-b52ad30fe0fa5464379a3fae6cb76a75L208.
A fix is now available in PR #29.
Since there was no CI at the time, the regression hadn't been detected.
It should not happen anymore in the future.

**Comment by cppcooper** [comment]
I'm working on making a [gcc compatible version of StackWalker](https://github.com/cppcooper/stackwalker-multi-plat). Right now I'm waiting for some fixes to the i686 build of [dbghelp2](https://github.com/vtjnash/dbghelp2). Once I've got the 32bit version of the dll I'll test your solution against the one a friend on Discord came up with; probably both work. I'll post an update.

**Comment by cppcooper** [comment]
It works. I actually tested with the macro defined with `RtlCaptureContext(&c);` as well, and it also works. Curious why both are needed.
